Euclideon/udcore

azure-pipelines-jobs-linux.yml
azure-pipelines-jobs-macos.yml
azure-pipelines-jobs-windows.yml
azure-pipelines.yml
udTest/src/udSocketTests.cpp

- Fixed SSL socket test
Supersedes #2

Added Azure Pipelines builds

---

Include/udMath.h
Include/udMath_Inl.h

Moved some unrelated function declarations for aesthetics

Added udVector template overloads for udRound

---

Include/udAsyncJob.h
Include/udCallback.h
Include/udThread.h
Include/udWorkerPool.h
Source/udCompression.cpp
Source/udThread.cpp
Source/udWorkerPool.cpp
premake5.lua
project.lua
udTest/project.lua
udTest/src/udAsyncJobTests.cpp
udTest/src/udCallbackTests.cpp
udTest/src/udThreadTests.cpp

- Improved udCallback by removing allocations
- Extended udCallback API
- Added missing header guards to udCallback
- Expanded unit tests for udCallback
- Added unit tests for udAsyncJob
- Added new udAsyncJob macro, UDASYNC_CALL that puts a function call inside a capturing lambda
- Updated to C++14

Converted APIs to use udCallback

---

Source/udResult.cpp
azure-pipelines-jobs-emscripten.yml
azure-pipelines.yml
premake5.lua

- Made changes to get building for latest Emscripten

Added Emscripten builds

---

Source/udGeoZone.cpp

Fixed issue with creating bounds for Datum JGD2000/LGD2011

---

3rdParty/stb/stb_image_write.h

Not currently used in this repo but almost every project built on top of this has needed it and udImage should wrap it as well.

Added stb_image_write.h

---

Source/udGeoZone.cpp

Fixed GeoZone transform function

---

Include/udPlatformUtil.h
Source/udPlatformUtil.cpp

- Forced format validation on all calls to SetFromFullPath

Fixed potential crash in udFilename when given path with a % in it

---

azure-pipelines-jobs-emscripten.yml
udTest/udTest.html
udTest/webtest.py

Unit tests are now run in Chrome for Emscripten builds

---

azure-pipelines-jobs-emscripten.yml
udTest/webtest.py

Also updated to be compatible with Python3.

Added support for testing with Firefox

---

azure-pipelines-jobs-emscripten.yml
azure-pipelines.yml

- Updated to latest docker image
- Use Python3 instead of Python2

Test Firefox in CI environment

---

Include/udPlatformUtil.h
Source/udFileHandler_FILE.cpp
Source/udPlatformUtil.cpp
udTest/src/udFileTests.cpp

Makes udFile recursively generate directories

Recursively generate directories

---

Source/udFile.cpp
Source/udFileHandler_FILE.cpp
udTest/webtest.py

- Unit tests now fail if they timeout
- udFile_TranslatePath now returns an error instead of crashing when called in Emscripten

Fixed various issues with Emscripten

---

Include/udGeoZone.h
Source/udGeoZone.cpp

I was going to add support for EPSG:2193 but it was already done, I just decided to clean a bit while browsing.

Keeping an ascending order in the epsg switch

---

Include/udGeoZone.h
Source/udGeoZone.cpp
udTest/src/udGeoZoneTests.cpp

Added support for Cassini and Stereographic Oblique Projections

Cassini and Stereographic Oblique Projections support

---

Include/udImage.h
Source/udImage.cpp
Source/udPlatformUtil.cpp
udTest/src/udImageTests.cpp

Added unit test for round-trip save/load
Note this pulls the stbi_write implementation into udCore, external projects may have to undefine STB_IMAGE_WRITE_IMPLEMENTATION

Added support for writing images using stbi

---

Include/udCallback.h
udTest/src/udCallbackTests.cpp

Fixes [AB#2482](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/2482)

Fixed numerous issues with udCallback implementation being wrong

---

Source/udJSON.cpp
Source/udThread.cpp
azure-pipelines-jobs-linux-containerless.yml
azure-pipelines.yml

Added build support for Ubuntu 20.04 Focal Fossa

---

Source/udCompression.cpp

Required for [AB#2781](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/2781)

Fixed potential infinite loop in zip file handler

---

Source/udGeoZone.cpp

refactored of Transverse Mercator Projection

---

Include/udPlatformUtil.h
Source/udPlatformUtil.cpp
udTest/src/udFilenameTests.cpp

- Added unit tests for udFilename

Fixed issues with udFilename not handling long paths

---

Include/udGeoZone.h
Source/udGeoZone.cpp
azure-pipelines-jobs-macos.yml
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5573](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5573)
Fixes [AB#5574](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5574)

Added Pulkovo 1942 and 1995 Datums

---

Include/udGeoZone.h
Source/udGeoZone.cpp
azure-pipelines-jobs-macos.yml
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5591](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5591)

Added WGS 72BE Datum

---

Include/udGeoZone.h
Source/udGeoZone.cpp
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5612](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5612)

hotine oblique mercator

---

Include/udGeoZone.h
Source/udGeoZone.cpp
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5621](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5621)

Added NZGD49 Fatum

---

Include/udGeoZone.h
Source/udGeoZone.cpp
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5623](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5623)

Added Albers Conic Equal Area Projection and test

---

Include/udGeoZone.h
Source/udGeoZone.cpp
udTest/src/udGeoZoneTests.cpp

Fixes [AB#5669](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5669)
Fixes [AB#5670](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/5670)

added SWEREF99 and SAD69 Datum

---

Source/udCrypto.cpp
azure-pipelines.yml

- Removed unused parameter and variable

Added build support for Ubuntu 22.04 Jammy Jellyfish

---

Include/udIntersectionTest.h
Source/udIntersectionTest.cpp

Problems were occurring with large numbers in geolocated models

Upgraded udIntersection test to use doubles

---

Source/udPlatform.cpp

Prior implementation crashes if the allocation fails

Rewrote udMemDup to not crash on failure

---

Source/udGeoZone.cpp

Fixes [AB#7137](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/7137)

Added mutex protection to internal udGeoZone data

---

azure-pipelines-jobs-emscripten.yml
azure-pipelines-jobs-linux.yml
azure-pipelines-jobs-windows.yml
azure-pipelines.yml
premake5.lua
project.lua
udTest/project.lua
udTest/server.py
udTest/webtest.py

- Updated Windows-based builds to use VS2022
- Updated Ubuntu 18.04 builds to build Premake beta2 from source
- Updated Emscripten builds to not use the Docker image
- Added Emscripten builds for the latest version of Emscripten
- Updated coverage build to use the Ubuntu VM provided by MS

Updated Premake binaries to use VS2022

---

Source/udThread.cpp

- Used dispatch_semaphore on macOS and iOS
- Removed custom semaphore implementation

Moved to platform-specific semaphores

---

Include/udChunkedArray.h
udTest/src/udChunkedArrayTests.cpp

- Added unit test to ensure that jumping backwards on an iterator works

Fixed issues with udChunkedArray iterators

---

Include/udImage.h
Source/udImage.cpp
udTest/src/udImageTests.cpp
udTest/webtest.py

Also includes the update for webtest.py to use Services

Split udImageStreaming_SaveAs into two parts

---

Docs/udJSON.md
udTest/src/udJSONTests.cpp

Also added hexfloat parsing and exporting to the tests

Minor change to mention hexfloats in the markdown

---

Source/udFile.cpp
udTest/src/udFileTests.cpp

Fixes [AB#8151](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/8151)

Added ability to deregister file handlers by prefix

---

Source/udThread.cpp

Added name of thread to thread debugging log
Changed name of cached threads waiting to be re-used to be obvious in debugger

Minor changes related to debugging threads

---

Include/udImage.h

Fixed bug in calculation of on-disk size of streaming textures

---

Source/udImage.cpp

Simplifies file closing logic on destruction

Made ImageStreaming add a reference to all files it reads from
